version: 2.1
executors:
  build_environment:
    docker:
      - image: circleci/ruby:2.6
        environment:
          BUNDLE_JOBS: 3
          BUNDLE_RETRY: 3
          BUNDLE_PATH: vendor/bundle

jobs:
  build:
    working_directory: ~/adhearsion-twilio
    executor:
      name: build_environment

    steps:
      - checkout

      - run:
          name: Upgrade Bundler
          command: |
            gem update --system
            gem install bundler

      - run:
          name: Bundle Install
          command: |
            bundle install

      - run:
          name: Run Specs
          command: bundle exec rspec

workflows:
  version: 2
  build:
    jobs:
      - build
