version: 2.1
executors:
  build_environment:
    docker:
      - image: circleci/ruby:2.6
        environment:
          BUNDLE_JOBS: 3
          BUNDLE_RETRY: 3
          BUNDLE_PATH: vendor/bundle

jobs:
  build:
    working_directory: ~/adhearsion-twilio
    executor:
      name: build_environment

    steps:
      - checkout

      - bundle_install:
          cache_name: "adhearsion-twilio-deps"

      - run:
          name: Run Specs
          command: bundle exec rspec

  upgrade_bundler:
    steps:
      - run:
          name: Upgrade Bundler
          command: |
            gem update --system
            gem install bundler

  bundle_install:
    parameters:
      cache_name:
        type: string
      bundle_install_path:
        type: string
        default: "."
      cache_path:
        type: string
        default: "vendor/bundle"

    steps:
      - upgrade_bundler
      - restore_cache:
          keys:
            - << parameters.cache_name >>-{{ checksum "Gemfile.lock" }}
            - << parameters.cache_name >>-

      - run:
          name: Bundle Install
          command: |
              cd << parameters.bundle_install_path >>
              BUNDLE_GEMFILE=Gemfile bundle install

      - save_cache:
          key: << parameters.cache_name >>-{{ checksum "Gemfile.lock" }}
          paths:
            - << parameters.cache_path >>

workflows:
  version: 2
  build:
    jobs:
      - build
